version: '3'

services:
  db:
    image: mariadb:latest
    container_name: npm_db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nginxproxymanager
      MYSQL_USER: nginxproxymanager
      MYSQL_PASSWORD: nginxproxymanager
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    depends_on:
      - db
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
